;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	transpose-sexps
	tuareg-electric-rp
	))

(setq mc/cmds-to-run-once
      '(
	python-indent-electric-colon
	))
