;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	LaTeX-insert-left-brace
	TeX-insert-backslash
	TeX-insert-dollar
	c-electric-paren
	kill-region
	transpose-sexps
	tuareg-electric-rp
	))

(setq mc/cmds-to-run-once
      '(
	electric-pair-delete-pair
	markdown-other-window
	python-indent-electric-colon
	yas-expand
	))
